server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 https://$host$request_uri;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

server {
    listen 443 ssl;
    server_name www.orctattoo.com.br;

    # Certificado SSL e chave privada configurados aqui
    ssl_certificate /etc/ssl/certs/orctattoo.crt;
    ssl_certificate_key /etc/ssl/private/orctattoo.key;

    location / {
        root /var/www/html;  # Diretório onde está o arquivo index.html
        index index.html;    # Nome do arquivo index.html

        # Configurações opcionais para arquivos estáticos
        gzip on;
        gzip_types text/plain text/css application/json application/javascript;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
    }
}
